### ISSUE TITLE
Do we need an Application Load balancer?

### ISSUE THREAD

**Issue by andyduong1920** [liamstevens111/terraform-infrastructure-example#15]

**Comment by liamstevens111** [comment]
Don't we? 🤔 

I have it included in the networking already (https://github.com/liamstevens111/terraform-infrastructure-example/pull/13). I can set target group to `IP` and when creating ECS use that target group / alb. ECS service should auto register the task IPS to the target group.

Only other alternative? is `ECS Service Discovery`

**Comment by andyduong1920** [comment]
Application load balance can becomes a separate module - along with the network stuff @liamstevens111 

- ALB: The AWS service, like RDS, Elashticsearch
- Network: The network inside the VPC

**Comment by liamstevens111** [comment]
is there a reason to have a separate module just for ALB? From my point of view it was encompassing a `network` together with vpc and things. I feel like if separate to a module it should encompass more things or be re-usable on its own, not a thin wrapper over an existing AWS service and not be re-usable. What do you think? Maybe I am wrong here as learning.

I do remember in docs you shouldn't have modules that are thin wrappers over existing services. And to add to that I don't think it's re-usable on its own?

**Comment by andyduong1920** [comment]
> Maybe I am wrong here as learning.

Yeah @liamstevens111, please check the load balancer docs again :)

**Comment by hoangmirs** [comment]
> I do remember in docs you shouldn't have modules that are thin wrappers over existing services. And to add to that I don't think it's re-usable on its own?

Yeah, from the [documentation](https://developer.hashicorp.com/terraform/language/modules):

> Modules are containers for multiple resources that are used together

And to use ALB, we might need: `aws_lb`, `aws_lb_target_group`, and `aws_lb_listener `. And we can put them into a module to manage them easily
