### ISSUE TITLE
Missing the CD part?

### ISSUE THREAD

**Issue by andyduong1920** [liamstevens111/terraform-infrastructure-example#16]

**Comment by liamstevens111** [comment]
Don't get what you mean? The CI/CD will be on the actual project repository I have to create from the template, no?

Terraform Cloud should automatically deploy from pull requests in this repository.

**Comment by andyduong1920** [comment]
The CD to deploy the app, yeah and it will be on the project repository, it's part of this IC, right @liamstevens111 ?

- Generate the project
- Setup the CD

**Comment by liamstevens111** [comment]
Yeah it's not clear where this project will live, in this repository (that I've named terraform infra) or a separate repo? Hmm

**Comment by andyduong1920** [comment]
You can decide to keep the project and the infra on the same repo or separate repository @liamstevens111 :D 

In normal client project, we keep it separately => so it's 2 repositotires

**Comment by liamstevens111** [comment]
Yeah issue added here 👍 - #19 

I will add a separate repo
